stages:
    - build
    - test

build website:
    image: node:16-alpine
    stage: build
    script:
        - cd frontEnd
        - cd carbooking
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build

test website:
    image: node:16-alpine
    stage: test
    script:
        - yarn global add serve
        - apk add curl
        - ls
        - cd frontEnd
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000 | grep "React App"

.unit test:
    image: node:16-alpine
    stage: test
    script:
        - cd frontEnd
        - cd carbooking
        - yarn install
        - yarn test


