stages:
    - build
    - test

build website:
    image: node:16-alpine
    stage: build
    script:
        - cd frontEnd
        - cd carbooking
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build

test website:
    image: node:16-alpine
    stage: test
    script:
        - yarn global add serve
        - ls
        - serve -s build

.unit test:
    image: node:16-alpine
    stage: test
    script:
        - cd frontEnd
        - cd carbooking
        - yarn install
        - yarn test


