stages:
    - build front
    - test
    - deploy front
    - post deploy
    - build

variables:
    FRONT_APP_URL: http://morgam-frontend.s3-website.us-east-2.amazonaws.com

.build website:
    image: node:16-alpine
    stage: build front
    script:
        - cd frontEnd
        - cd carbooking
        - yarn install
        - yarn build
    artifacts:
        paths:
            - frontEnd/carbooking/build

.test website:
    image: node:16-alpine
    stage: test
    script:
        - yarn global add serve
        - apk add curl
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000

.unit test:
    image: node:16-alpine
    stage: test
    script:
        - cd frontEnd
        - cd carbooking
        - yarn install
        - yarn test

.deploy to s3:
    stage: deploy front
    image: 
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    script:
        - aws --version
        - aws s3 sync frontEnd/carbooking/build s3://$AWS_S3_BUCKET --delete

.deploy to s3 2:
    stage: deploy front
    image: 
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    script:
        - aws --version
        - echo $CI_COMMIT_REF_NAME
        - aws s3 sync frontEnd/carbooking/build s3://$AWS_S3_BUCKET --delete

.pre-production test:
    stage: post deploy
    image: curlimages/curl
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    script:
        - curl $FRONT_APP_URL

build:
    stage: build
    image:  maven:latest
    script:
        - cd backend
        - cd demo
        - ls
        - mvn clean install
        - ls
    artifacts:
        expire_in: 1 week
        paths:
            - backend/demo/target/consoleapp-2.7.2.jar


