stages:
    - build
    - test
    - deploy

build website:
    image: node:16-alpine
    stage: build
    script:
        - cd frontEnd
        - cd carbooking
        - yarn install
        - yarn build
    artifacts:
        paths:
            - frontEnd/carbooking/build

.test website:
    image: node:16-alpine
    stage: test
    script:
        - yarn global add serve
        - apk add curl
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000

.unit test:
    image: node:16-alpine
    stage: test
    script:
        - cd frontEnd
        - cd carbooking
        - yarn install
        - yarn test

deploy to s3:
    stage: deploy
    image: 
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    script:
        - aws --version
        - aws s3 sync frontEnd/carbooking/build s3://$AWS_S3_BUCKET --delete


